In [74]:
import requests

try:
    print("Loading shared code from GitHub...")
    url = 'https://raw.githubusercontent.com/peterdresslar/Dresslar_CAS522/main/src/shared.py'
    response = requests.get(url)
    response.raise_for_status()
    exec(response.text)
    print("Successfully loaded shared code.")
except requests.exceptions.RequestException as e:
    print(f"Failed to load code from GitHub: {e}")
    print("\nPlease ensure you have an internet connection, or place the shared.py file in a 'src' directory next to this notebook.")

Loading shared code from GitHub...
Successfully loaded shared code.


## Dresslar CAS522 M6 Notebook


In [75]:
import os
import sys
import numpy as np
import itertools
from collections import OrderedDict

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

from src.shared import int_less_than_21_to_word  # adjust if needed


Consider the dynamics of the following Boolean network (Fig. 1.)

<br />
<img src="../public/Assignment Module 6-1.png" width="400px"/> <br />
<span text-size="small"><em>Figure 1</em><span>
<br />


### Question 1
> Determine the global dynamics of the network by finding all cycles and fix-point attractors. Determine the sizes of all basins of attraction. Perform the analysis without using any numerical code.

To begin, we should describe this diagram in the same manner as (Gros p.80): this is a boolean network with $N = 4$ sites and connectivities $K_i = 2$. The diagram as it is contains "network linkage and coupling functions." We should be able to use these to diagram the network dynamics.

Figure 2 contains the (hand-drawn) "complete network dynamics" (Gros p.80), along with a complete state table on the right side of the image.

<br />
<img src="../public/M6_dynamics.jpg" width="500px"/> <br />
<span text-size="small"><em>Figure 2</em><span>
<br /> <br />

From this diagram that we can see that we have two fixpoint attractors, `0000` and `1111`, each of which supplies a basin of attraction for a two transient states (respectively: `0001`, `0100` and `0111`, `1101`). We also have a length 2 cyclic attractor `0101 <--> 1010`: interestingly, while `1010` captures only the output of `0101`, the latter is the entrypoint of the cyclic basin for all the remaining transient states.


### Question 2
> Then double-check your results in python, and submit your notebook. 

Terrific! No more dry-erase zeroes for today.


In [76]:
# State, following Gros:
N = 4
K = 2
figure = 1

state = np.zeros(N, dtype=bool)

def f_sigma_1(state):
    return state[1] & state[3]

def f_sigma_2(state):
    return state[0] | state[2]

def f_sigma_3(state):
    return state[1] & state[3]

def f_sigma_4(state):
    return state[0] | state[2]

def update(state):
    sigma_0 = f_sigma_1(state)
    sigma_1 = f_sigma_2(state)
    sigma_2 = f_sigma_3(state)
    sigma_3 = f_sigma_4(state)
    state = np.array([sigma_0, sigma_1, sigma_2, sigma_3])
    return state

# okay, it is very easy to simply compute all 2^N states and their first updates,
# this should look just like the right side of my whiteboard.
print("start --> next")
for i in range(2**N):
    # many ways to do this but let's be explict by converting i to binary:
    i_bin = np.binary_repr(i, width=N)
    # now we can write i_bin to state:
    state = np.array([int(x) for x in i_bin])  # this is kind of cheating but works fine
    # and then we can simply print the state and its update:
    print(f"{state} --> {update(state)}")


start --> next
[0 0 0 0] --> [0 0 0 0]
[0 0 0 1] --> [0 0 0 0]
[0 0 1 0] --> [0 1 0 1]
[0 0 1 1] --> [0 1 0 1]
[0 1 0 0] --> [0 0 0 0]
[0 1 0 1] --> [1 0 1 0]
[0 1 1 0] --> [0 1 0 1]
[0 1 1 1] --> [1 1 1 1]
[1 0 0 0] --> [0 1 0 1]
[1 0 0 1] --> [0 1 0 1]
[1 0 1 0] --> [0 1 0 1]
[1 0 1 1] --> [0 1 0 1]
[1 1 0 0] --> [0 1 0 1]
[1 1 0 1] --> [1 1 1 1]
[1 1 1 0] --> [0 1 0 1]
[1 1 1 1] --> [1 1 1 1]


In [77]:
# But now we want to find all cycles and fix-point attractors. We are fortunate to have a useful constraint, here: no cycle
# can be longer than 2^N = 16 steps. Thus, brute force is easy. So, the following might be a useful overview, if not exactly what we want.

print("start --> sigma_1 --> sigma_2 --> ... --> sigma_2^N")
for i in range(2**N):
    i_bin = np.binary_repr(i, width=N)
    state = np.array([int(x) for x in i_bin])
    # and then we can piece together a single line of update outputs:
    line = f"{state}"
    for j in range(2**N):
        new_state = update(state)
        line += f" --> {new_state}"
        state = new_state
    print(line)

start --> sigma_1 --> sigma_2 --> ... --> sigma_2^N
[0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0]
[0 0 0 1] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0]
[0 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0]
[0 0 1 1] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0]
[0 1 0 0] --

In [78]:
# .... We are going to need to do a lot better. Basically we need to track our states and search. What we can see from the view above is that
# the pattern we are searching for is when a state *repeats* in the sequence. Then, the sequence of states between repeats is our cycle. We might 
# track that sequence as an array, since our first and last states are important for us to understand our system dynamics.
# (commented prints can be uncommented to see the process)

def get_idx_of_np_array_in_list(np_array_to_check, list_np_arrays):
    # returns -1 if not found: otherwise returns index of first occurence
    #print(f"list_np_arrays: {len(list_np_arrays)}")
    for i, arr in enumerate(list_np_arrays):
        #print(f"testing {np_array_to_check} against {arr}")
        if np.array_equal(np_array_to_check, arr):
            #print(f"found at index {i}")
            return i
    return -1


print("start --> cycle: cycle length")
print("--------------------------------")
for i in range(2**N):
    i_bin = np.binary_repr(i, width=N)
    starting_state = np.array([int(x) for x in i_bin])
    state = starting_state
    path = [state]
    while True:
        new_state = update(state)
        # check j_vals to see if there is already an entry for new_state
        # note we are using numpy, so it is a bit more work to check if an array is in a list of arrays
        idx_if_present = get_idx_of_np_array_in_list(new_state, path)  # get index or -1
        if idx_if_present > -1: # we have seen this state before
            cycle_start = idx_if_present
            cycle = path[idx_if_present:] 
            print(f"{i_bin} --> {cycle}: cycle length {len(cycle)}")
            break
        state = new_state
        path.append(new_state)



start --> cycle: cycle length
--------------------------------
0000 --> [array([0, 0, 0, 0])]: cycle length 1
0001 --> [array([0, 0, 0, 0])]: cycle length 1
0010 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0011 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0100 --> [array([0, 0, 0, 0])]: cycle length 1
0101 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0110 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0111 --> [array([1, 1, 1, 1])]: cycle length 1
1000 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1001 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1010 --> [array([1, 0, 1, 0]), array([0, 1, 0, 1])]: cycle length 2
1011 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1100 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1101 --> [array([1, 1, 1, 1])]: cycle length 1
1110 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1111 --> [array([1, 1,

This is a nice "first" attempt at getting the information we want about system dynamics, but a few tweaks will allow us to clean up the data. We especially need to "de-duplicate" the cycles and we want to be able to count and size them so that we can deliver a "textbook" answer (again, Gros (p. 80))

In [79]:
# reporting structures
cycles_report = ""
fixpoints_report = ""
total_states = 0
number_fixpoints = 0
cycles_list = [] # here we store the actual cycles as a list of strings
answer_template = "In Fig. {figure} a network with N = {N} and K = {K} is fully defined. The time evolution of the `2^{N}` = {total_states} states Σt is given for synchronous updating. One can observe {cycles_report} and {fixpoints_report}."

def cycle_to_string(cycle):
    """Inputs:
    [array([0, 1, 0, 1]), array([1, 0, 1, 0])]
    Outputs:
    ['0101', '1010']
    """
    out = []
    for c in cycle:
        out.append("".join([str(int(not x)) for x in c]))
    return out

def test_if_cycle_identical(cycle1, cycle2):
    """
    Inputs:
    ['0101', '1010', foo, bar]
    ['1010', foo, bar,'0101']
    Outputs:
    True
    """
    identical = False
    if len(cycle1) != len(cycle2):
        return identical
    for i, cyc1 in enumerate(cycle1):
        for j, cyc2 in enumerate(cycle2):
            # find the element i in cycle2
            if cyc1 == cyc2:
                # create two new lists with i, j as the starting indicies
                cyc1_new = cycle1[i:] + cycle1[:i]
                cyc2_new = cycle2[j:] + cycle2[:j]
                if cyc1_new == cyc2_new:
                    identical = True

    return identical

# c1 = ['0101', '1010', 'foo', 'bar']
# c2 = ['1010', 'foo', 'bar', '0101']
# print(test_if_cycle_identical(c1, c2))
# True (Hooray!)

def remove_duplicates(cycles_list):
    """
    Inputs:
    [['0101', '1010'], ['0101', '1010']]
    Outputs:
    [['0101', '1010']]
    """

    # print(type(cycles_list), type(cycles_list[0]), type(cycles_list[0][0]))
    # <class 'list'> <class 'list'> <class 'str'>

    # First we do the easy part:
    # we need to remove all exact duplicates
    # https://stackoverflow.com/a/2213973

    print(cycles_list)
    k = sorted(cycles_list, key=lambda x: x[0])  # sorted to return new list
    print(k)
    dedup = list(k for k,_ in itertools.groupby(k))
    print(dedup)

    # now we downshift back to a list
    cl = list(dedup)

    # now with our remaining list, we need to check each cycle against every other cycle
    for _, cycle_m in enumerate(cl):
        for n, cycle_n in enumerate(cl):
            if test_if_cycle_identical(cycle_m, cycle_n):
                cl.pop(n)
    return cl

some_cycles = [['0101', '1010'], ['0101', '1010'], ['1000'], ['1000']]
print(remove_duplicates(some_cycles))
    
for i in range(2**N):
    i_bin = np.binary_repr(i, width=N)
    starting_state = np.array([int(x) for x in i_bin])
    state = starting_state
    path = [starting_state]
    while True:
        new_state = update(state)
        idx_if_present = get_idx_of_np_array_in_list(new_state, path)
        if idx_if_present > -1:
            cycle_start = idx_if_present
            cycle = path[idx_if_present:] 
            cycles_list.append(cycle_to_string(cycle))
            break
        state = new_state
        path.append(new_state)

print(cycles_list)
cycles_list = remove_duplicates(cycles_list)
print(cycles_list)
# for reporting.... lots of data manipulation
number_cycles = OrderedDict()
for cycle in cycles_list:
    cycle_length = len(cycle)
    if cycle_length in number_cycles:
        number_cycles[cycle_length] += 1
    else:
        number_cycles[cycle_length] = 1

number_cycles = OrderedDict(sorted(number_cycles.items()))

for cycle_length, count in number_cycles.items():
    cycles_report += f"{int_less_than_21_to_word(cycle_length)} cycles of length {cycle_length} ({count}x), "

fixpoints_report = f"{int_less_than_21_to_word(number_fixpoints)} cycles of length 1 (fixpoints)"

answer = answer_template.format(
    figure=figure,
    N=N,
    K=K,
    total_states=2**N,
    cycles_report=cycles_report,
    fixpoints_report=fixpoints_report
)


print(answer)



[['0101', '1010'], ['0101', '1010'], ['1000'], ['1000']]
[['0101', '1010'], ['0101', '1010'], ['1000'], ['1000']]
[['0101', '1010'], ['1000']]
[['1000']]
[['1111'], ['1111'], ['1010', '0101'], ['1010', '0101'], ['1111'], ['1010', '0101'], ['1010', '0101'], ['0000'], ['1010', '0101'], ['1010', '0101'], ['0101', '1010'], ['1010', '0101'], ['1010', '0101'], ['0000'], ['1010', '0101'], ['0000']]
[['1111'], ['1111'], ['1010', '0101'], ['1010', '0101'], ['1111'], ['1010', '0101'], ['1010', '0101'], ['0000'], ['1010', '0101'], ['1010', '0101'], ['0101', '1010'], ['1010', '0101'], ['1010', '0101'], ['0000'], ['1010', '0101'], ['0000']]
[['0000'], ['0000'], ['0000'], ['0101', '1010'], ['1010', '0101'], ['1010', '0101'], ['1010', '0101'], ['1010', '0101'], ['1010', '0101'], ['1010', '0101'], ['1010', '0101'], ['1010', '0101'], ['1010', '0101'], ['1111'], ['1111'], ['1111']]
[['0000'], ['0101', '1010'], ['1010', '0101'], ['1111']]
[['1010', '0101'], ['1111']]
In Fig. 1 a network with N = 4 and K 