## Dresslar CAS522 M6 Notebook

Consider the dynamics of the following Boolean network (Fig. 1.)

<br />
<img src="../public/Assignment Module 6-1.png" width="400px"/> <br />
<span text-size="small"><em>Figure 1</em><span>
<br />


### Question 1
> Determine the global dynamics of the network by finding all cycles and fix-point attractors. Determine the sizes of all basins of attraction. Perform the analysis without using any numerical code.

To begin, we should describe this diagram in the same manner as (Gros p.80): this is a boolean network with $N = 4$ sites and connectivities $K_i = 2$. The diagram as it is contains "network linkage and coupling functions." We should be able to use these to diagram the network dynamics.

Figure 2 contains the (hand-drawn) "complete network dynamics" (Gros p.80), along with a complete state table on the right side of the image.

<br />
<img src="../public/M6_dynamics.jpg" width="500px"/> <br />
<span text-size="small"><em>Figure 2</em><span>
<br /> <br />

From this diagram that we can see that we have two fixpoint attractors, `0000` and `1111`, each of which supplies a basin of attraction for a two transient states (respectively: `0001`, `0100` and `0111`, `1101`). We also have a length 2 cyclic attractor `0101 <--> 1010`: interestingly, while `1010` captures only the output of `0101`, the latter is the entrypoint of the cyclic basin for all the remaining transient states.


### Question 2
> Then double-check your results in python, and submit your notebook. 

Terrific! No more dry-erase zeroes for today.


In [105]:
# Okay, fun time.

# State, following Gros:
import numpy as np

N = 4

state = np.zeros(N, dtype=bool)

def f_sigma_1(state):
    return state[1] & state[3]

def f_sigma_2(state):
    return state[0] | state[2]

def f_sigma_3(state):
    return state[1] & state[3]

def f_sigma_4(state):
    return state[0] | state[2]

def update(state):
    sigma_0 = f_sigma_1(state)
    sigma_1 = f_sigma_2(state)
    sigma_2 = f_sigma_3(state)
    sigma_3 = f_sigma_4(state)
    state = np.array([sigma_0, sigma_1, sigma_2, sigma_3])
    return state

# okay, it is very easy to simply compute all 2^N states and their first updates,
# this should look just like the right side of my whiteboard.
print("start --> next")
for i in range(2**N):
    # many ways to do this but let's be explict by converting i to binary:
    i_bin = np.binary_repr(i, width=N)
    # now we can write i_bin to state:
    state = np.array([int(x) for x in i_bin])  # this is kind of cheating but works fine
    # and then we can simply print the state and its update:
    print(f"{state} --> {update(state)}")


start --> next
[0 0 0 0] --> [0 0 0 0]
[0 0 0 1] --> [0 0 0 0]
[0 0 1 0] --> [0 1 0 1]
[0 0 1 1] --> [0 1 0 1]
[0 1 0 0] --> [0 0 0 0]
[0 1 0 1] --> [1 0 1 0]
[0 1 1 0] --> [0 1 0 1]
[0 1 1 1] --> [1 1 1 1]
[1 0 0 0] --> [0 1 0 1]
[1 0 0 1] --> [0 1 0 1]
[1 0 1 0] --> [0 1 0 1]
[1 0 1 1] --> [0 1 0 1]
[1 1 0 0] --> [0 1 0 1]
[1 1 0 1] --> [1 1 1 1]
[1 1 1 0] --> [0 1 0 1]
[1 1 1 1] --> [1 1 1 1]


In [106]:
# But now we want to find all cycles and fix-point attractors. We are fortunate to have a useful constraint, here: no cycle
# can be longer than 2^N = 16 steps. Thus, brute force is easy. So, the following might be a useful overview, if not exactly what we want.

print("start --> sigma_1 --> sigma_2 --> ... --> sigma_2^N")
for i in range(2**N):
    i_bin = np.binary_repr(i, width=N)
    state = np.array([int(x) for x in i_bin])
    # and then we can piece together a single line of update outputs:
    line = f"{state}"
    for j in range(2**N):
        new_state = update(state)
        line += f" --> {new_state}"
        state = new_state
    print(line)


start --> sigma_1 --> sigma_2 --> ... --> sigma_2^N
[0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0]
[0 0 0 1] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0] --> [0 0 0 0]
[0 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0]
[0 0 1 1] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0] --> [0 1 0 1] --> [1 0 1 0]
[0 1 0 0] --

In [108]:
# .... We are going to need to do a lot better. Basically we need to track our states and search. What we can see from the view above is that
# the pattern we are searching for is when a state *repeats* in the sequence. Then, the sequence of states between repeats is our cycle. We might 
# track that sequence as an array, since our first and last states are important for us to understand our system dynamics.
# (commented prints can be uncommented to see the process)

def get_idx_of_np_array_in_list(np_array_to_check, list_np_arrays):
    # returns -1 if not found: otherwise returns index of first occurence
    #print(f"list_np_arrays: {len(list_np_arrays)}")
    for i, arr in enumerate(list_np_arrays):
        #print(f"testing {np_array_to_check} against {arr}")
        if np.array_equal(np_array_to_check, arr):
            #print(f"found at index {i}")
            return i
    return -1


print("start --> cycle: cycle length")
print("--------------------------------")
for i in range(2**N):
    i_bin = np.binary_repr(i, width=N)
    starting_state = np.array([int(x) for x in i_bin])
    state = starting_state
    path = [state]
    while True:
        new_state = update(state)
        # check j_vals to see if there is already an entry for new_state
        # note we are using numpy, so it is a bit more work to check if an array is in a list of arrays
        idx_if_present = get_idx_of_np_array_in_list(new_state, path)  # get index or -1
        if idx_if_present > -1: # we have seen this state before
            cycle_start = idx_if_present
            cycle = path[idx_if_present:] 
            print(f"{i_bin} --> {cycle}: cycle length {len(cycle)}")
            break
        state = new_state
        path.append(new_state)



start --> cycle: cycle length
--------------------------------
0000 --> [array([0, 0, 0, 0])]: cycle length 1
0001 --> [array([0, 0, 0, 0])]: cycle length 1
0010 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0011 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0100 --> [array([0, 0, 0, 0])]: cycle length 1
0101 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0110 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
0111 --> [array([1, 1, 1, 1])]: cycle length 1
1000 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1001 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1010 --> [array([1, 0, 1, 0]), array([0, 1, 0, 1])]: cycle length 2
1011 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1100 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1101 --> [array([1, 1, 1, 1])]: cycle length 1
1110 --> [array([0, 1, 0, 1]), array([1, 0, 1, 0])]: cycle length 2
1111 --> [array([1, 1,